# Generated by Django 5.0.6 on 2024-10-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrossCheck', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='testcases',
            name='scriptName',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
        migrations.AddField(
            model_name='testcases',
            name='testProfile',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
    ]
