# Generated by Django 5.0.6 on 2024-11-21 03:17

import CrossCheck.utils.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrossCheck', '0003_sysusers_testcases_scriptname_testcases_testprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8, unique=True)),
                ('sequence', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.CharField(default=CrossCheck.utils.id_generator.generate_custom_id, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('suite', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('testprofile', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('createdby', models.CharField(max_length=10)),
                ('updatedby', models.CharField(max_length=10)),
            ],
        ),
    ]
