# Generated by Django 5.0.6 on 2024-11-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrossCheck', '0004_idgenerator_testcase'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testcase',
            table='cc_testcase',
        ),
    ]
